In [2]:
#聚合函数
#可以直接用 np.sum(),或者 data.sum().
#参数 axis=0 表示行聚合
import numpy as np
data = np.arange(12).reshape(3,4)
print data.sum(axis = 0),data.sum(axis = 1)

[12 15 18 21] [ 6 22 38]


In [4]:
#类似的聚合函数还有 prod(积)，argmin(最小元素的索引)，mean(均值)，std(标准差)，var(方差)，median(中位数).percentile(分位数)
#最好还是用 np.prob 防止出错
#若忽略空值的话，直接在函数前面加上"nan",  np.nansum()
print np.percentile(data,25),np.median(data),np.percentile(data,75)   #四分位数

2.75 5.5 8.25


In [5]:
#聚合函数还有  np.all() 检验所有的值是否是都是True，np.any() 检验在所有条件中是否有True
np.all(data==3)  #检验是否所有数据都等于3
np.any(data==3)  #检验是否有数据等于3

True

In [7]:
#花式索引
#可以累加的方法
#在x索引上，对应的a加1
a = np.zeros(10)
x = [2,3,3,4,4,4]  #索引
np.add.at(a,x,1)   #对应的索引分别加一
a

array([ 0.,  0.,  1.,  2.,  3.,  0.,  0.,  0.,  0.,  0.])

In [10]:
#指定输出，在数据量大的情况下使用
#不用生成临时数组，直接储存在y中
x = np.arange(5)
y = np.empty(5)
z = np.zeros(10)
np.multiply(x,10,out = y)
np.power(x,5,out = z[::2])  #储存在z中，每隔两个元素
y,z

(array([  0.,  10.,  20.,  30.,  40.]),
 array([  0.00000000e+00,   0.00000000e+00,   1.00000000e+00,
          0.00000000e+00,   3.20000000e+01,   0.00000000e+00,
          2.43000000e+02,   0.00000000e+00,   1.02400000e+03,
          0.00000000e+00]))

In [11]:
#numpy排序
x = np.array([5,3,6,1,2])
np.sort(x)    #返回一个排好序的数组，不改变原数组
index = np.argsort(x)     #返回排好序后元素的索引
x[index]     #同样返回一个排好序的数组

array([1, 2, 3, 5, 6])

In [15]:
#分隔
data = np.random.randint(0,10,(4,5))
data,np.partition(data,2,axis=1)    #每一行的前两个数字是这一行的最小的两个值
data1 = np.random.randint(0,10,10)
data1,np.partition(data1,3)    #数组中前三个元素就是最小的三个元素

(array([7, 5, 8, 7, 5, 6, 1, 2, 2, 8]), array([2, 1, 2, 5, 5, 6, 7, 7, 8, 8]))