In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
#Series(data,index=index),
#index默认就是按顺序的整数
#data数据类型可以是  列表，numpy列表，一个标量，一个字典
data = Series([1,2,3,4])
data1 = Series({"a":1,"b":2,"c":3,"d":4,"e":5},index = ["a","b","c","d"])      #字典的键值就是index,后面的index参数是选择指定的指标
data2 = Series(5,index=[0,1,2,3])

In [3]:
#可以用python字典的方式选取
print("a" in data1)           #True
print(data1.keys())           #选择data1的index
print(list(data1.items()))    #键值对

True
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]


In [4]:
#显示性index，包含切片末尾的索引
print (data1["a":"d"])
#隐示性index，和列表数组一样
print (data1[:4])
#布尔型掩码
data1[(data1>=2)&(data1<=4)]
#花式索引
data1[["a","b"]]

a    1
b    2
c    3
d    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


a    1
b    2
dtype: int64

In [5]:
#隐示和显示索引的区别  loc（显示）,iloc（隐示）,ix（混合）
""" loc,iloc,ix [行，列]，[行]"""
data = Series(list("abcde"),index = [1,3,5,7,9])
print (data.loc[1:3])       #显示索引
print (data.iloc[:2])         #隐示索引

1    a
3    b
dtype: object
1    a
3    b
dtype: object


In [6]:
#DataFrame转变成narray
data = DataFrame(np.arange(12).reshape(3,4),columns = list("abcd"),index = [1,3,5])
print(data.values)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
###切片，花式，布尔掩码，
print (data.loc[data["a"]>1,["a","d"]])     #loc可以花式，布尔掩码一起使用
print (data.iloc[1:,[0,3]])                 #iloc可以花式，不可以布尔掩码

   a   d
3  4   7
5  8  11
   a   d
3  4   7
5  8  11


In [8]:
###其他提数的方式
print (data["a"])        #单个标签值  选取的是列
print (data[:2])         #多个标签切片  选取的是行
print (data[data["a"]>1])    #布尔掩码  选取的也是行

1    0
3    4
5    8
Name: a, dtype: int32
   a  b  c  d
1  0  1  2  3
3  4  5  6  7
   a  b   c   d
3  4  5   6   7
5  8  9  10  11


In [9]:
####Frame或Series同类的数据运算
#是运用DataFrame的属性方法，DataFrame.add(，，fill_value=？)处理缺失值的时候
#sub(),div(),mul(),floordiv(),pow()

####dataframe和Series之间的数据运算"""
#计算时保留索引，和numpy 计算类似 广播的方式

In [10]:
#处理缺失值的方式
#DataFrame.isnull(),notnull(),dropna(),fillna()
data = Series([1,None,2,None,3,4])
data.fillna(0)    #全部以0填充
data.fillna(method = "ffill")      #向前填充数据，向后填充数据参数是 "bfill"
data.dropna()     #去除所有的缺失值，DataFrame中默剔除所有行，用axis调整；how="all"表示剔除所有是np.nan的行或列；

0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [11]:
#DataFrame，多索引的Series相互转变
data1 = DataFrame(np.arange(12).reshape(3,4),columns = list("abcd"),index = np.arange(2000,2003))
data1.stack()    #转变为多索引的Series,参数level在多重索引中使用
data1.stack().unstack()     #多索引的Series转变为DataFrame

a  b   c   d
2000  0  1   2   3
2001  4  5   6   7
2002  8  9  10  11

In [15]:
#创建多重索引的方式
index = pd.MultiIndex(levels=[["a","b"],[1,2]],labels=[[0,0,1,1],[0,1,0,1]])
columns = pd.MultiIndex.from_product([["it","he","she"],["temp","hr"]])
print (pd.MultiIndex(levels=[["a","b"],[1,2]],labels=[[0,0,1,1],[0,1,0,1]]))
print (pd.MultiIndex.from_arrays([["a","a","b","b"],[1,2,1,2]]) )
print (pd.MultiIndex.from_tuples([("a",0),("a",1),("b",0),("b",1)]) )
print (pd.MultiIndex.from_product([["a","b"],[1,2]]) )

#接着直接创建DataFrame,也可以在列上创建多维数据
data = DataFrame(np.random.randint(1,10,(4,6)),index = index,columns = columns)
data

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])
MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])
MultiIndex(levels=[['a', 'b'], [0, 1]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])
MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])


it      he     she   
    temp hr temp hr temp hr
a 1    5  4    3  7    5  7
  2    7  9    6  2    5  6
b 1    4  8    6  8    5  4
  2    1  3    5  6    3  1

In [16]:
#多维数据的索取
data["he","hr"]
data.iloc[:2,[0,1,2]]   #iloc是常规的选择，按照顺序

#loc的选择方法很不一样
data.loc[:,"she"]    #可行，错误方式[:,["he","she"]] , [:,"he":"she"]
data.loc["a":"b",:]   #可行

it      he     she   
    temp hr temp hr temp hr
a 1    5  4    3  7    5  7
  2    7  9    6  2    5  6
b 1    4  8    6  8    5  4
  2    1  3    5  6    3  1

In [18]:
idx = pd.IndexSlice  #创建一个分隔方式

#######若想执行这一步必须得对内外索引进行排序！！！！！！！！！！，不然会出错
#所以多重索引必须先把索引排序
data = data.sort_index(axis=1)
data.loc[idx[:,1],idx[:,"hr"]]        

he it she
    hr hr  hr
a 1  7  4   7
b 1  8  8   4

In [28]:
##对某一个数据进行排序
df = pd.DataFrame(np.random.randint(1,10,(4,4)),columns = list("dcba"))
arr = pd.Series([3,1,2,5,8,4])
#对DataFrame的某个列的值大小进行排序 或 对Series的值进行排序
df.sort_values(by = "a")  
arr.sort_values()
#对DataFrame,Series的值大小标注序号，类似 np.argsort()
df.rank(axis=1,method="average")    #method参数有很多种 min,max,first

1    1
2    2
0    3
5    4
3    5
4    8
dtype: int64