In [1]:
import pandas as pd
import numpy as np
from pandas import Series,DataFrame

In [2]:
#Series(data,index=index),
#index默认就是按顺序的整数
#data数据类型可以是  列表，numpy列表，一个标量，一个字典
data = Series([1,2,3,4])
data1 = Series({"a":1,"b":2,"c":3,"d":4,"e":5},index = ["a","b","c","d"])      #字典的键值就是index,后面的index参数是选择指定的指标
data2 = Series(5,index=[0,1,2,3])

In [3]:
#可以用python字典的方式选取
print("a" in data1)           #True
print(data1.keys())           #选择data1的index
print(list(data1.items()))    #键值对

True
Index(['a', 'b', 'c', 'd'], dtype='object')
[('a', 1), ('b', 2), ('c', 3), ('d', 4)]


In [4]:
#显示性index，包含切片末尾的索引
print (data1["a":"d"])
#隐示性index，和列表数组一样
print (data1[:4])
#布尔型掩码
data1[(data1>=2)&(data1<=4)]
#花式索引
data1[["a","b"]]

a    1
b    2
c    3
d    4
dtype: int64
a    1
b    2
c    3
d    4
dtype: int64


a    1
b    2
dtype: int64

In [5]:
#隐示和显示索引的区别  loc（显示）,iloc（隐示）,ix（混合）
""" loc,iloc,ix [行，列]，[行]"""
data = Series(list("abcde"),index = [1,3,5,7,9])
print (data.loc[1:3])       #显示索引
print (data.iloc[:2])         #隐示索引

1    a
3    b
dtype: object
1    a
3    b
dtype: object


In [6]:
#DataFrame转变成narray
data = DataFrame(np.arange(12).reshape(3,4),columns = list("abcd"),index = [1,3,5])
print(data.values)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [7]:
###切片，花式，布尔掩码，
print (data.loc[data["a"]>1,["a","d"]])     #loc可以花式，布尔掩码一起使用
print (data.iloc[1:,[0,3]])                 #iloc可以花式，不可以布尔掩码

   a   d
3  4   7
5  8  11
   a   d
3  4   7
5  8  11


In [8]:
###其他提数的方式
print (data["a"])        #单个标签值  选取的是列
print (data[:2])         #多个标签切片  选取的是行
print (data[data["a"]>1])    #布尔掩码  选取的也是行

1    0
3    4
5    8
Name: a, dtype: int32
   a  b  c  d
1  0  1  2  3
3  4  5  6  7
   a  b   c   d
3  4  5   6   7
5  8  9  10  11


In [9]:
####Frame或Series同类的数据运算
#是运用DataFrame的属性方法，DataFrame.add(，，fill_value=？)处理缺失值的时候
#sub(),div(),mul(),floordiv(),pow()

####dataframe和Series之间的数据运算"""
#计算时保留索引，和numpy 计算类似 广播的方式

In [10]:
#处理缺失值的方式
#DataFrame.isnull(),notnull(),dropna(),fillna()
data = Series([1,None,2,None,3,4])
data.fillna(0)    #全部以0填充
data.fillna(method = "ffill")      #向前填充数据，向后填充数据参数是 "bfill"
data.dropna()     #去除所有的缺失值，DataFrame中默剔除所有行，用axis调整；how="all"表示剔除所有是np.nan的行或列；

0    1.0
2    2.0
4    3.0
5    4.0
dtype: float64

In [11]:
#DataFrame，多索引的Series相互转变
data1 = DataFrame(np.arange(12).reshape(3,4),columns = list("abcd"),index = np.arange(2000,2003))
data1.stack()    #转变为多索引的Series,参数level在多重索引中使用
data1.stack().unstack()     #多索引的Series转变为DataFrame

a  b   c   d
2000  0  1   2   3
2001  4  5   6   7
2002  8  9  10  11

In [15]:
#创建多重索引的方式
index = pd.MultiIndex(levels=[["a","b"],[1,2]],labels=[[0,0,1,1],[0,1,0,1]])
columns = pd.MultiIndex.from_product([["it","he","she"],["temp","hr"]])
print (pd.MultiIndex(levels=[["a","b"],[1,2]],labels=[[0,0,1,1],[0,1,0,1]]))
print (pd.MultiIndex.from_arrays([["a","a","b","b"],[1,2,1,2]]) )
print (pd.MultiIndex.from_tuples([("a",0),("a",1),("b",0),("b",1)]) )
print (pd.MultiIndex.from_product([["a","b"],[1,2]]) )

#接着直接创建DataFrame,也可以在列上创建多维数据
data = DataFrame(np.random.randint(1,10,(4,6)),index = index,columns = columns)
data

MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])
MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])
MultiIndex(levels=[['a', 'b'], [0, 1]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])
MultiIndex(levels=[['a', 'b'], [1, 2]],
           labels=[[0, 0, 1, 1], [0, 1, 0, 1]])


it      he     she   
    temp hr temp hr temp hr
a 1    5  4    3  7    5  7
  2    7  9    6  2    5  6
b 1    4  8    6  8    5  4
  2    1  3    5  6    3  1

In [16]:
#多维数据的索取
data["he","hr"]
data.iloc[:2,[0,1,2]]   #iloc是常规的选择，按照顺序

#loc的选择方法很不一样
data.loc[:,"she"]    #可行，错误方式[:,["he","she"]] , [:,"he":"she"]
data.loc["a":"b",:]   #可行

it      he     she   
    temp hr temp hr temp hr
a 1    5  4    3  7    5  7
  2    7  9    6  2    5  6
b 1    4  8    6  8    5  4
  2    1  3    5  6    3  1

In [18]:
idx = pd.IndexSlice  #创建一个分隔方式

#######若想执行这一步必须得对内外索引进行排序！！！！！！！！！！，不然会出错
#所以多重索引必须先把索引排序
data = data.sort_index(axis=1)
data.loc[idx[:,1],idx[:,"hr"]]        

he it she
    hr hr  hr
a 1  7  4   7
b 1  8  8   4

In [28]:
##对某一个数据进行排序
df = pd.DataFrame(np.random.randint(1,10,(4,4)),columns = list("dcba"))
arr = pd.Series([3,1,2,5,8,4])
#对DataFrame的某个列的值大小进行排序 或 对Series的值进行排序
df.sort_values(by = "a")  
arr.sort_values()
#对DataFrame,Series的值大小标注序号，类似 np.argsort()
df.rank(axis=1,method="average")    #method参数有很多种 min,max,first

1    1
2    2
0    3
5    4
3    5
4    8
dtype: int64

In [2]:
import seaborn as sns
plants = sns.load_dataset('planets')
plants

method  number  orbital_period    mass  distance  year
0     Radial Velocity       1      269.300000   7.100     77.40  2006
1     Radial Velocity       1      874.774000   2.210     56.95  2008
2     Radial Velocity       1      763.000000   2.600     19.84  2011
3     Radial Velocity       1      326.030000  19.400    110.62  2007
4     Radial Velocity       1      516.220000  10.500    119.47  2009
5     Radial Velocity       1      185.840000   4.800     76.39  2008
6     Radial Velocity       1     1773.400000   4.640     18.15  2002
7     Radial Velocity       1      798.500000     NaN     21.41  1996
8     Radial Velocity       1      993.300000  10.300     73.10  2008
9     Radial Velocity       2      452.800000   1.990     74.79  2010
10    Radial Velocity       2      883.000000   0.860     74.79  2010
11    Radial Velocity       1      335.100000   9.880     39.43  2009
12    Radial Velocity       1      479.100000   3.880     97.28  2008
13    Radial Velocity       3     1078.000000   2.530     14.08  1996
14    Radial Velocity       3     2391.000000   0.540     14.08  2001
15    Radial Velocity       3    14002.000000   1.640     14.08  2009
16    Radial Velocity       1        4.230785   0.472     15.36  1995
17    Radial Velocity       5       14.651000   0.800     12.53  1996
18    Radial Velocity       5       44.380000   0.165     12.53  2004
19    Radial Velocity       5     4909.000000   3.530     12.53  2002
20    Radial Velocity       5        0.736540     NaN     12.53  2011
21    Radial Velocity       5      261.200000   0.172     12.53  2007
22    Radial Velocity       3        4.215000   0.016      8.52  2009
23    Radial Velocity       3       38.021000   0.057      8.52  2009
24    Radial Velocity       3      123.010000   0.072      8.52  2009
25    Radial Velocity       1      116.688400     NaN     18.11  1996
26    Radial Velocity       1      691.900000     NaN     81.50  2012
27    Radial Velocity       1      952.700000   5.300     97.18  2008
28    Radial Velocity       1      181.400000   3.200     45.52  2013
29            Imaging       1             NaN     NaN     45.52  2005
...               ...     ...             ...     ...       ...   ...
1005          Transit       1        3.693641     NaN    200.00  2012
1006          Transit       1        4.465633     NaN    330.00  2012
1007          Transit       1        4.617101     NaN    255.00  2012
1008          Transit       1        2.838971     NaN    455.00  2012
1009          Transit       1        5.017180     NaN    300.00  2012
1010          Transit       1        7.919585     NaN    125.00  2012
1011          Transit       1        4.305001     NaN    400.00  2012
1012          Transit       1        3.855900     NaN    480.00  2012
1013          Transit       1        4.411953     NaN    160.00  2012
1014          Transit       1        4.378090     NaN    330.00  2012
1015          Transit       1        1.573292     NaN    350.00  2012
1016          Transit       1        2.311424     NaN    310.00  2013
1017          Transit       1        4.086052     NaN    380.00  2012
1018          Transit       1        4.614420     NaN    225.00  2012
1019          Transit       1        2.903675     NaN    345.00  2012
1020          Transit       1        2.216742     NaN    340.00  2012
1021          Transit       1        2.484193     NaN    260.00  2013
1022          Transit       1        1.360031     NaN     93.00  2012
1023          Transit       1        2.175176     NaN    550.00  2012
1024          Transit       1        3.662387     NaN    240.00  2012
1025          Transit       1        3.067850     NaN     60.00  2012
1026          Transit       1        0.925542     NaN    470.00  2014
1027          Imaging       1             NaN     NaN     19.20  2011
1028          Transit       1        3.352057     NaN   3200.00  2012
1029          Imaging       1             NaN     NaN     10.10  2012
1030          Transit    

In [6]:
decade = (plants["year"]//10)*10
decade = decade.astype(str)+"s"
# decade.name = "decade"
decade

0       2000s
1       2000s
2       2010s
3       2000s
4       2000s
5       2000s
6       2000s
7       1990s
8       2000s
9       2010s
10      2010s
11      2000s
12      2000s
13      1990s
14      2000s
15      2000s
16      1990s
17      1990s
18      2000s
19      2000s
20      2010s
21      2000s
22      2000s
23      2000s
24      2000s
25      1990s
26      2010s
27      2000s
28      2010s
29      2000s
        ...  
1005    2010s
1006    2010s
1007    2010s
1008    2010s
1009    2010s
1010    2010s
1011    2010s
1012    2010s
1013    2010s
1014    2010s
1015    2010s
1016    2010s
1017    2010s
1018    2010s
1019    2010s
1020    2010s
1021    2010s
1022    2010s
1023    2010s
1024    2010s
1025    2010s
1026    2010s
1027    2010s
1028    2010s
1029    2010s
1030    2000s
1031    2000s
1032    2000s
1033    2000s
1034    2000s
Name: year, Length: 1035, dtype: object

In [7]:
plants.groupby(["method",decade])["number"].sum().unstack().fillna(0)

year                           1980s  1990s  2000s  2010s
method                                                   
Astrometry                       0.0    0.0    0.0    2.0
Eclipse Timing Variations        0.0    0.0    5.0   10.0
Imaging                          0.0    0.0   29.0   21.0
Microlensing                     0.0    0.0   12.0   15.0
Orbital Brightness Modulation    0.0    0.0    0.0    5.0
Pulsar Timing                    0.0    9.0    1.0    1.0
Pulsation Timing Variations      0.0    0.0    1.0    0.0
Radial Velocity                  1.0   52.0  475.0  424.0
Transit                          0.0    0.0   64.0  712.0
Transit Timing Variations        0.0    0.0    0.0    9.0

In [8]:
titanic = sns.load_dataset('titanic')

In [10]:
titanic.groupby('sex')[['survived']].mean()

survived
sex             
female  0.742038
male    0.188908